server:
  port: 8787


gitlab:
  webhooks:
    - id: finance
      way: DING_MESSAGE
      config:
        access-token: 93a93799cde9xxxxxx655ae0d4eb9872883c
        sign-key: SECcd68c6b173cca046231c48739c6141a891c9
    - id: order
      way: FEI_SHU_MESSAGE
      config:
        url: https://open.feishu.cn/open-apis/bot/v2/hook/4ad2ff7d-78e4-4ef0-84be-ee6
        sign:
    - id: ware
      way: WECHAT_MESSAGE
      config:
        key: 11910fa


spring:
  application:
    name: @artifactId@
  banner:
    location: banner.txt
